stages:
  - build
  - test
  - publish
  - deploy

cache:
  paths:
    - frontend/node_modules/

build-backend:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - cd backend
    - dotnet restore
    - dotnet publish -c Release -o publish
  artifacts:
    paths:
      - backend/publish/
    expire_in: 1 hour

build-frontend:
  stage: build
  image: node:18-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 hour

test-backend:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - cd backend
    - dotnet test || true
  allow_failure: true

publish-artifacts:
  stage: publish
  image: curlimages/curl:latest
  script:
    - cd backend/publish && tar czf /tmp/app.tar.gz .
    - |
      curl -v -u "${NEXUS_USER}:${NEXUS_PASSWORD}" \
        --upload-file /tmp/app.tar.gz \
        "${NEXUS_URL}/repository/raw-hosted/${CI_PROJECT_NAME}/app.tar.gz"
    - |
      curl -v -u "${NEXUS_USER}:${NEXUS_PASSWORD}" \
        --upload-file docker-compose.yml \
        "${NEXUS_URL}/repository/raw-hosted/${CI_PROJECT_NAME}/docker-compose.yml"
    - |
      curl -v -u "${NEXUS_USER}:${NEXUS_PASSWORD}" \
        --upload-file backend/Dockerfile \
        "${NEXUS_URL}/repository/raw-hosted/${CI_PROJECT_NAME}/backend/Dockerfile"
    - |
      curl -v -u "${NEXUS_USER}:${NEXUS_PASSWORD}" \
        --upload-file frontend/Dockerfile \
        "${NEXUS_URL}/repository/raw-hosted/${CI_PROJECT_NAME}/frontend/Dockerfile"
  dependencies:
    - build-backend
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache ansible openssh-client
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true
  script:
    - |
      ansible-playbook -i "${DEPLOY_HOST}," \
        -u "${DEPLOY_USER}" \
        --private-key ~/.ssh/id_rsa \
        ansible/deploy-csharp-vue-docker.yml \
        -e "project_name=${CI_PROJECT_NAME}" \
        -e "nexus_url=${NEXUS_URL}" \
        -e "db_name=${CI_PROJECT_NAME}_db"
  environment:
    name: production
    url: http://${DEPLOY_HOST}:3000
  only:
    - main
  when: manual