stages:
  - build
  - test
  - deploy

backend-build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - cd backend
    - dotnet restore
    - dotnet build --no-restore

backend-test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - cd backend
    - dotnet test

frontend-build:
  stage: build
  image: node:20-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
  only:
    - main
  when: manual