stages:
  - build
  - test
  - publish
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/
    - frontend/node_modules/

# ── Backend Build ──
build-backend:
  stage: build
  image: maven:3.9-eclipse-temurin-17-alpine
  script:
    - cd backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
    expire_in: 1 hour

# ── Frontend Build ──
build-frontend:
  stage: build
  image: node:18-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 hour

# ── Backend Tests ──
test-backend:
  stage: test
  image: maven:3.9-eclipse-temurin-17-alpine
  script:
    - cd backend
    - mvn test
  allow_failure: true

# ── Publish to Nexus ──
publish-artifacts:
  stage: publish
  image: curlimages/curl:latest
  script:
    # Upload JAR to Nexus
    - |
      curl -v -u "${NEXUS_USER}:${NEXUS_PASSWORD}" \
        --upload-file backend/target/*.jar \
        "${NEXUS_URL}/repository/maven-releases/com/example/${CI_PROJECT_NAME}/$(date +%Y%m%d%H%M%S)/${CI_PROJECT_NAME}.jar"
    # Upload docker-compose
    - |
      curl -v -u "${NEXUS_USER}:${NEXUS_PASSWORD}" \
        --upload-file docker-compose.yml \
        "${NEXUS_URL}/repository/raw-hosted/${CI_PROJECT_NAME}/docker-compose.yml"
    # Upload Dockerfiles
    - |
      curl -v -u "${NEXUS_USER}:${NEXUS_PASSWORD}" \
        --upload-file backend/Dockerfile \
        "${NEXUS_URL}/repository/raw-hosted/${CI_PROJECT_NAME}/backend/Dockerfile"
    - |
      curl -v -u "${NEXUS_USER}:${NEXUS_PASSWORD}" \
        --upload-file frontend/Dockerfile \
        "${NEXUS_URL}/repository/raw-hosted/${CI_PROJECT_NAME}/frontend/Dockerfile"
  dependencies:
    - build-backend
  only:
    - main

# ── Deploy ──
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache ansible openssh-client
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true
  script:
    - |
      ansible-playbook -i "${DEPLOY_HOST}," \
        -u "${DEPLOY_USER}" \
        --private-key ~/.ssh/id_rsa \
        ansible/deploy-java-react-docker.yml \
        -e "project_name=${CI_PROJECT_NAME}" \
        -e "nexus_url=${NEXUS_URL}" \
        -e "db_name=${CI_PROJECT_NAME}_db"
  environment:
    name: production
    url: http://${DEPLOY_HOST}:3000
  only:
    - main
  when: manual