stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/
    - frontend/node_modules

backend-build:
  stage: build
  image: python:3.11
  script:
    - cd backend
    - pip install -r requirements.txt

backend-test:
  stage: test
  image: python:3.11
  script:
    - cd backend
    - pip install -r requirements.txt
    - python manage.py test

frontend-build:
  stage: build
  image: node:20-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
  only:
    - main
  when: manual