stages:
  - build
  - test
  - publish
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/
    - frontend/node_modules/

build-backend:
  stage: build
  image: maven:3.9-eclipse-temurin-17-alpine
  script:
    - cd backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
    expire_in: 1 hour

build-frontend:
  stage: build
  image: node:18-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 hour

test-backend:
  stage: test
  image: maven:3.9-eclipse-temurin-17-alpine
  script:
    - cd backend
    - mvn test
  allow_failure: true

publish-artifacts:
  stage: publish
  image: curlimages/curl:latest
  script:
    - |
      curl -v -u "${NEXUS_USER}:${NEXUS_PASSWORD}" \
        --upload-file backend/target/*.jar \
        "${NEXUS_URL}/repository/maven-releases/com/example/${CI_PROJECT_NAME}/$(date +%Y%m%d%H%M%S)/${CI_PROJECT_NAME}.jar"
  dependencies:
    - build-backend
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache ansible openssh-client
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true
  script:
    - |
      ansible-playbook -i "${DEPLOY_HOST}," \
        -u "${DEPLOY_USER}" \
        --private-key ~/.ssh/id_rsa \
        ansible/deploy-java-vue-no-docker.yml \
        -e "project_name=${CI_PROJECT_NAME}" \
        -e "jar_path=backend/target/*.jar" \
        -e "frontend_dist=frontend/dist/" \
        -e "db_name=${CI_PROJECT_NAME}_db"
  environment:
    name: production
  only:
    - main
  when: manual