stages:
  - build
  - sonar
  - docker
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository
    - frontend/node_modules

# ==========================================
# Backend Build & Test
# ==========================================

backend-build:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - cd backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
    expire_in: 1 hour

backend-test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  script:
    - cd backend
    - mvn test
  artifacts:
    when: always
    reports:
      junit:
        - backend/target/surefire-reports/*.xml

# ==========================================
# Frontend Build
# ==========================================

frontend-build:
  stage: build
  image: node:20-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 hour

# ==========================================
# SonarQube Analysis
# ==========================================

sonarqube:
  stage: sonar
  image: maven:3.9-eclipse-temurin-17
  script:
    - cd backend
    - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.token=$SONAR_TOKEN
  allow_failure: true
  only:
    - main
    - develop

# ==========================================
# Docker Build & Push
# ==========================================

docker-build:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA ./backend
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA ./frontend
    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/backend:latest
    - docker tag $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/frontend:latest
    - docker push $CI_REGISTRY_IMAGE/backend:latest
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
  only:
    - main
    - tags

# ==========================================
# Deploy
# ==========================================

deploy-staging:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying to staging..."
  environment:
    name: staging
    url: http://staging.{{PROJECT_NAME_DASH}}.local
  only:
    - main
  when: manual

deploy-production:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying to production..."
  environment:
    name: production
    url: http://{{PROJECT_NAME_DASH}}.local
  only:
    - tags
  when: manual