stages:
  - build
  - test
  - publish
  - deploy

cache:
  paths:
    - frontend/node_modules/

build-backend:
  stage: build
  image: python:3.11-slim
  script:
    - cd backend
    - pip install -r requirements.txt
    - python manage.py check

build-frontend:
  stage: build
  image: node:18-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 hour

test-backend:
  stage: test
  image: python:3.11-slim
  script:
    - cd backend
    - pip install -r requirements.txt
    - python manage.py test || true
  allow_failure: true

publish-artifacts:
  stage: publish
  image: curlimages/curl:latest
  script:
    - echo "No Docker artifacts to publish"
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache ansible openssh-client
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true
  script:
    - |
      ansible-playbook -i "${DEPLOY_HOST}," \
        -u "${DEPLOY_USER}" \
        --private-key ~/.ssh/id_rsa \
        ansible/deploy-python-react-no-docker.yml \
        -e "project_name=${CI_PROJECT_NAME}" \
        -e "db_name=${CI_PROJECT_NAME}_db"
  environment:
    name: production
  only:
    - main
  when: manual